import turtle
wn = turtle.Screen()
wn.title('Κατασκευη γραμματων Α,Β,C,Δ')
scale = 8
## Letter A
turtle.down ( )
# Point upwards to begin
turtle.left ( turtle.heading ( ) + 90 )
turtle.right ( 20 )
turtle.forward ( 10 * scale )
turtle.right ( 70 )
turtle.forward ( 1 * scale )
turtle.right ( 70 )
turtle.forward ( 10 * scale )
turtle.backward ( 5 * scale )
turtle.right ( 90 + 20 )
turtle.forward ( 5 * scale )
#Move to right of letter and over 1 * scale
turtle.up ( )
turtle.backward ( 5 * scale )
turtle.left ( 110 )
turtle.forward ( 5 * scale )
turtle.left ( 70 )
turtle.forward ( 1 * scale )

## Letter B
turtle.down ( )
# Point upwards to begin
turtle.left ( turtle.heading ( ) + 90 )
turtle.forward ( 10 * scale )
turtle.right ( 90 )
turtle.forward ( 4 * scale )
turtle.right ( 90 )
turtle.forward ( 4 * scale )
turtle.left ( 90 )
turtle.backward ( 1 * scale )
turtle.forward ( 2 * scale )
turtle.right ( 90 )
turtle.forward ( 6 * scale )
turtle.right ( 90 )
turtle.forward ( 5 * scale )
# Move to right of letter
turtle.up ( )
turtle.right ( 180 )
turtle.forward ( 6 * scale )

## Letter C
turtle.down ( )
# Point upwards to begin
turtle.left ( turtle.heading ( ) + 90 )
turtle.forward ( 10 * scale )
turtle.right ( 90 )
turtle.forward ( 4 * scale )
turtle.backward ( 4 * scale )
turtle.left ( 90 )
turtle.backward ( 10 * scale )
turtle.right ( 90 )
turtle.forward ( 4 * scale )
# Move to right of letter
turtle.up ( )
turtle.forward ( 1 * scale )

#leter D
turtle.down ( )
# Point upwards to begin
turtle.left ( turtle.heading ( ) + 90 )
turtle.right ( 20 )
turtle.forward ( 10 * scale )
turtle.right ( 70 )
turtle.forward ( 1 * scale )
turtle.right ( 70 )
turtle.forward ( 10 * scale )
#turtle.backward ( 10 * scale )
turtle.right ( 14 * scale )
turtle.forward ( 70  )
# Pause
#input ( "Press any key to end." )
print( "Press any key to end." )
wn.exitonclick()

import turtle
import math
wn = turtle.Screen()
wn.title('Κατασκευη φακελου')
sideLength = 160
halfDiagonalLength = 0.5 * math.sqrt ( 2 * ( sideLength ** 2 ) )
# Create the right orientation.
turtle.left ( 90 )
# Draw the house.
turtle.forward ( sideLength )
turtle.right ( 135 )
turtle.forward ( halfDiagonalLength )
turtle.right ( 90 )
turtle.forward ( halfDiagonalLength )
turtle.left ( 135 )
turtle.forward ( sideLength )
turtle.left ( 135 )
turtle.forward ( halfDiagonalLength )
turtle.right ( 90 )
turtle.forward ( halfDiagonalLength )
turtle.left ( 135 )
turtle.forward ( sideLength )
turtle.right ( 135 )
turtle.forward ( halfDiagonalLength )
turtle.right ( 90 )
turtle.forward ( halfDiagonalLength )
turtle.right ( 45 )
turtle.forward ( sideLength )
# Prompt to stop the program from terminating and hence the display from disappearing.
turtle.left (90 )
#input ( 'Press return to terminate the program: ' )
wn.exitonclick()

import turtle
wn = turtle.Screen()
wn.title('Κατασκευη 3 κυκλων σε μαυρο κυκλο')
#turtle.color("black", "red")
#turtle.begin_fill()
#turtle.circle(80)
#turtle.end_fill()
turtle.up ( )
turtle.goto ( 0 , 35 )
turtle.down ( )
turtle.color ( 'black','red' )
turtle.begin_fill()
turtle.circle ( 20 )
turtle.end_fill()
turtle.up ( )
turtle.goto ( 0 , -20 )
turtle.down ( )
turtle.color ('black', 'yellow' )
turtle.begin_fill ()
turtle.circle ( 20 )
turtle.end_fill (  )
turtle.up ( )
turtle.goto ( 0 , -75 )
turtle.down ( )
turtle.color ('black', 'green' )
turtle.begin_fill (  )
turtle.circle ( 20 )
turtle.end_fill (  )
print ( "Press any key to end." )
wn.exitonclick()
#import turtle
#turtle.color("black", "red")
#turtle.begin_fill()
#turtle.circle(80)
#turtle.end_fill()
import turtle
wn = turtle.Screen()
wn.title('Κατασκευη 3 κυκλων')
def drawAtWithColor ( x , y , c ) :
     turtle.up ( )
     turtle.goto ( x , y )
     turtle.down ( )
     turtle.color ( c )
     turtle.circle ( 20 )
drawAtWithColor ( 0 , 35 , 'red' )
drawAtWithColor ( 0 , -20 , 'yellow' )
drawAtWithColor ( 0 , -75 , 'green' )
#input ( 'Press return to terminate the program: ' )
print ( "Press any key to end." )
wn.exitonclick()
